/* SPDX-License-Identifier: GPL-2.0-or-later
 * Message crackers (HANDLE_MSG, HANDLE_WM_* and FORWARD_WM_*), the portable
 * GET_WM_* unpacking macros, and control, GDI and memory helper macros, as
 * Windows programs of the 3.1 era used them. Messages are packed as in Win32;
 * with WIN16_MESSAGES defined before windows.h, the crackers and GET_WM_*
 * take Windows 3.0's packing instead. */
#ifndef _WINDOWSX_H
#define _WINDOWSX_H
#include <windows.h>

#define HANDLE_MSG(hwnd,message,fn) case (message): return HANDLE_##message((hwnd),(wParam),(lParam),(fn))
#define HANDLE_WM_CREATE(hwnd,wParam,lParam,fn) (LRESULT)((fn)((hwnd),(LPCREATESTRUCT)(lParam))?0L:(LRESULT)-1L)
#define FORWARD_WM_CREATE(hwnd,lpCreateStruct,fn) (fn)((hwnd),WM_CREATE,0L,(LPARAM)(LPCREATESTRUCT)(lpCreateStruct))
#define HANDLE_WM_NCCREATE(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(BOOL)(fn)((hwnd),(LPCREATESTRUCT)(lParam))
#define FORWARD_WM_NCCREATE(hwnd,lpCreateStruct,fn) (fn)((hwnd),WM_NCCREATE,0L,(LPARAM)(LPCREATESTRUCT)(lpCreateStruct))
#define HANDLE_WM_DESTROY(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_DESTROY(hwnd,fn) (fn)((hwnd),WM_DESTROY,0L,0L)
#define HANDLE_WM_NCDESTROY(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_NCDESTROY(hwnd,fn) (fn)((hwnd),WM_NCDESTROY,0L,0L)
#define HANDLE_WM_CLOSE(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_CLOSE(hwnd,fn) (fn)((hwnd),WM_CLOSE,0L,0L)
#define HANDLE_WM_PAINT(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_PAINT(hwnd,fn) (fn)((hwnd),WM_PAINT,0L,0L)
#define HANDLE_WM_QUIT(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(wParam)),0L)
#define FORWARD_WM_QUIT(hwnd,exitCode,fn) (fn)((hwnd),WM_QUIT,(WPARAM)(exitCode),0L)
#define HANDLE_WM_QUERYENDSESSION(hwnd,wParam,lParam,fn) MAKELRESULT((BOOL)(fn)(hwnd),0L)
#define FORWARD_WM_QUERYENDSESSION(hwnd,fn) (fn)((hwnd),WM_QUERYENDSESSION,0L,0L)
#define HANDLE_WM_ENDSESSION(hwnd,wParam,lParam,fn) ((fn)((hwnd),(BOOL)(wParam)),0L)
#define FORWARD_WM_ENDSESSION(hwnd,fEnding,fn) (fn)((hwnd),WM_ENDSESSION,(WPARAM)(BOOL)(fEnding),0L)
#define HANDLE_WM_MOVE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam)),0L)
#define FORWARD_WM_MOVE(hwnd,x,y,fn) (fn)((hwnd),WM_MOVE,0L,MAKELPARAM((x),(y)))
#define HANDLE_WM_SIZE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam)),0L)
#define FORWARD_WM_SIZE(hwnd,state,cx,cy,fn) (fn)((hwnd),WM_SIZE,(WPARAM)(UINT)(state),MAKELPARAM((cx),(cy)))
#define HANDLE_WM_ACTIVATE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)LOWORD(wParam),(HWND)(lParam),(BOOL)HIWORD(wParam)),0L)
#define FORWARD_WM_ACTIVATE(hwnd,state,hwndActDeact,fMinimized,fn) (fn)((hwnd),WM_ACTIVATE,MAKEWPARAM((state),(fMinimized)),(LPARAM)(HWND)(hwndActDeact))
#define HANDLE_WM_ACTIVATEAPP(hwnd,wParam,lParam,fn) ((fn)((hwnd),(BOOL)(wParam),(DWORD)(lParam)),0L)
#define FORWARD_WM_ACTIVATEAPP(hwnd,fActivate,dwThreadId,fn) (fn)((hwnd),WM_ACTIVATEAPP,(WPARAM)(BOOL)(fActivate),(LPARAM)(dwThreadId))
#define HANDLE_WM_SETFOCUS(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(wParam)),0L)
#define FORWARD_WM_SETFOCUS(hwnd,hwndOldFocus,fn) (fn)((hwnd),WM_SETFOCUS,(WPARAM)(HWND)(hwndOldFocus),0L)
#define HANDLE_WM_KILLFOCUS(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(wParam)),0L)
#define FORWARD_WM_KILLFOCUS(hwnd,hwndNewFocus,fn) (fn)((hwnd),WM_KILLFOCUS,(WPARAM)(HWND)(hwndNewFocus),0L)
#define HANDLE_WM_ENABLE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(BOOL)(wParam)),0L)
#define FORWARD_WM_ENABLE(hwnd,fEnable,fn) (fn)((hwnd),WM_ENABLE,(WPARAM)(BOOL)(fEnable),0L)
#define HANDLE_WM_SHOWWINDOW(hwnd,wParam,lParam,fn) ((fn)((hwnd),(BOOL)(wParam),(UINT)(lParam)),0L)
#define FORWARD_WM_SHOWWINDOW(hwnd,fShow,status,fn) (fn)((hwnd),WM_SHOWWINDOW,(WPARAM)(BOOL)(fShow),(LPARAM)(UINT)(status))
#define HANDLE_WM_ERASEBKGND(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(BOOL)(fn)((hwnd),(HDC)(wParam))
#define FORWARD_WM_ERASEBKGND(hwnd,hdc,fn) (fn)((hwnd),WM_ERASEBKGND,(WPARAM)(HDC)(hdc),0L)
#define HANDLE_WM_SETCURSOR(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(BOOL)(fn)((hwnd),(HWND)(wParam),(UINT)LOWORD(lParam),(UINT)HIWORD(lParam))
#define FORWARD_WM_SETCURSOR(hwnd,hwndCursor,codeHitTest,msg,fn) (fn)((hwnd),WM_SETCURSOR,(WPARAM)(HWND)(hwndCursor),MAKELPARAM((codeHitTest),(msg)))
#define HANDLE_WM_GETMINMAXINFO(hwnd,wParam,lParam,fn) ((fn)((hwnd),(LPMINMAXINFO)(lParam)),0L)
#define FORWARD_WM_GETMINMAXINFO(hwnd,lpMinMaxInfo,fn) (fn)((hwnd),WM_GETMINMAXINFO,0L,(LPARAM)(LPMINMAXINFO)(lpMinMaxInfo))
#define HANDLE_WM_SETFONT(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HFONT)(wParam),(BOOL)(lParam)),0L)
#define FORWARD_WM_SETFONT(hwnd,hfont,fRedraw,fn) (fn)((hwnd),WM_SETFONT,(WPARAM)(HFONT)(hfont),(LPARAM)(BOOL)(fRedraw))
#define HANDLE_WM_GETFONT(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HFONT)(fn)(hwnd)
#define FORWARD_WM_GETFONT(hwnd,fn) (fn)((hwnd),WM_GETFONT,0L,0L)
#define HANDLE_WM_KEYDOWN(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),TRUE,(int)(short)LOWORD(lParam),(UINT)HIWORD(lParam)),0L)
#define HANDLE_WM_KEYUP(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),FALSE,(int)(short)LOWORD(lParam),(UINT)HIWORD(lParam)),0L)
#define HANDLE_WM_SYSKEYDOWN(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),TRUE,(int)(short)LOWORD(lParam),(UINT)HIWORD(lParam)),0L)
#define HANDLE_WM_SYSKEYUP(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),FALSE,(int)(short)LOWORD(lParam),(UINT)HIWORD(lParam)),0L)
#define HANDLE_WM_CHAR(hwnd,wParam,lParam,fn) ((fn)((hwnd),(TCHAR)(wParam),(int)(short)LOWORD(lParam)),0L)
#define FORWARD_WM_CHAR(hwnd,ch,cRepeat,fn) (fn)((hwnd),WM_CHAR,(WPARAM)(TCHAR)(ch),MAKELPARAM((cRepeat),0))
#define HANDLE_WM_SYSCHAR(hwnd,wParam,lParam,fn) ((fn)((hwnd),(TCHAR)(wParam),(int)(short)LOWORD(lParam)),0L)
#define FORWARD_WM_SYSCHAR(hwnd,ch,cRepeat,fn) (fn)((hwnd),WM_SYSCHAR,(WPARAM)(TCHAR)(ch),MAKELPARAM((cRepeat),0))
#define HANDLE_WM_MOUSEMOVE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define FORWARD_WM_MOUSEMOVE(hwnd,x,y,keyFlags,fn) (fn)((hwnd),WM_MOUSEMOVE,(WPARAM)(UINT)(keyFlags),MAKELPARAM((x),(y)))
#define HANDLE_WM_LBUTTONDOWN(hwnd,wParam,lParam,fn) ((fn)((hwnd),FALSE,(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define HANDLE_WM_LBUTTONDBLCLK(hwnd,wParam,lParam,fn) ((fn)((hwnd),TRUE,(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define HANDLE_WM_LBUTTONUP(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define FORWARD_WM_LBUTTONUP(hwnd,x,y,keyFlags,fn) (fn)((hwnd),WM_LBUTTONUP,(WPARAM)(UINT)(keyFlags),MAKELPARAM((x),(y)))
#define HANDLE_WM_RBUTTONDOWN(hwnd,wParam,lParam,fn) ((fn)((hwnd),FALSE,(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define HANDLE_WM_RBUTTONDBLCLK(hwnd,wParam,lParam,fn) ((fn)((hwnd),TRUE,(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define HANDLE_WM_RBUTTONUP(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define FORWARD_WM_RBUTTONUP(hwnd,x,y,keyFlags,fn) (fn)((hwnd),WM_RBUTTONUP,(WPARAM)(UINT)(keyFlags),MAKELPARAM((x),(y)))
#define HANDLE_WM_MBUTTONDOWN(hwnd,wParam,lParam,fn) ((fn)((hwnd),FALSE,(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define HANDLE_WM_MBUTTONUP(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam),(UINT)(wParam)),0L)
#define FORWARD_WM_MBUTTONUP(hwnd,x,y,keyFlags,fn) (fn)((hwnd),WM_MBUTTONUP,(WPARAM)(UINT)(keyFlags),MAKELPARAM((x),(y)))
#define HANDLE_WM_TIMER(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam)),0L)
#define FORWARD_WM_TIMER(hwnd,id,fn) (fn)((hwnd),WM_TIMER,(WPARAM)(UINT)(id),0L)
#define HANDLE_WM_HSCROLL(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(lParam),(UINT)(LOWORD(wParam)),(int)(short)HIWORD(wParam)),0L)
#define FORWARD_WM_HSCROLL(hwnd,hwndCtl,code,pos,fn) (fn)((hwnd),WM_HSCROLL,MAKEWPARAM((UINT)(int)(code),(UINT)(int)(pos)),(LPARAM)(HWND)(hwndCtl))
#define HANDLE_WM_VSCROLL(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(lParam),(UINT)(LOWORD(wParam)),(int)(short)HIWORD(wParam)),0L)
#define FORWARD_WM_VSCROLL(hwnd,hwndCtl,code,pos,fn) (fn)((hwnd),WM_VSCROLL,MAKEWPARAM((UINT)(int)(code),(UINT)(int)(pos)),(LPARAM)(HWND)(hwndCtl))
#define HANDLE_WM_INITMENU(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HMENU)(wParam)),0L)
#define FORWARD_WM_INITMENU(hwnd,hMenu,fn) (fn)((hwnd),WM_INITMENU,(WPARAM)(HMENU)(hMenu),0L)
#define HANDLE_WM_INITMENUPOPUP(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HMENU)(wParam),(UINT)LOWORD(lParam),(BOOL)HIWORD(lParam)),0L)
#define FORWARD_WM_INITMENUPOPUP(hwnd,hMenu,item,fSystemMenu,fn) (fn)((hwnd),WM_INITMENUPOPUP,(WPARAM)(HMENU)(hMenu),MAKELPARAM((item),(fSystemMenu)))
#define HANDLE_WM_MENUSELECT(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HMENU)(lParam),(HIWORD(wParam)&MF_POPUP)?0L:(int)(LOWORD(wParam)),(HIWORD(wParam)&MF_POPUP)?GetSubMenu((HMENU)lParam,LOWORD(wParam)):0L,(UINT)(((short)HIWORD(wParam)==-1)?0xFFFFFFFF:HIWORD(wParam))),0L)
#define HANDLE_WM_MENUCHAR(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(fn)((hwnd),(UINT)(LOWORD(wParam)),(UINT)HIWORD(wParam),(HMENU)(lParam))
#define FORWARD_WM_MENUCHAR(hwnd,ch,flags,hmenu,fn) (fn)((hwnd),WM_MENUCHAR,(WPARAM)MAKELONG(ch,flags),(LPARAM)(HMENU)(hmenu))
#define HANDLE_WM_COMMAND(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(LOWORD(wParam)),(HWND)(lParam),(UINT)HIWORD(wParam)),0L)
#define FORWARD_WM_COMMAND(hwnd,id,hwndCtl,codeNotify,fn) (fn)((hwnd),WM_COMMAND,MAKEWPARAM((UINT)(id),(UINT)(codeNotify)),(LPARAM)(HWND)(hwndCtl))
#define HANDLE_WM_SYSCOMMAND(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam)),0L)
#define FORWARD_WM_SYSCOMMAND(hwnd,cmd,x,y,fn) (fn)((hwnd),WM_SYSCOMMAND,(WPARAM)(UINT)(cmd),MAKELPARAM((x),(y)))
#define HANDLE_WM_INITDIALOG(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(UINT)(BOOL)(fn)((hwnd),(HWND)(wParam),lParam)
#define FORWARD_WM_INITDIALOG(hwnd,hwndFocus,lParam,fn) (fn)((hwnd),WM_INITDIALOG,(WPARAM)(HWND)(hwndFocus),(lParam))
#define HANDLE_WM_DRAWITEM(hwnd,wParam,lParam,fn) ((fn)((hwnd),(const DRAWITEMSTRUCT *)(lParam)),0L)
#define FORWARD_WM_DRAWITEM(hwnd,lpDrawItem,fn) (fn)((hwnd),WM_DRAWITEM,(WPARAM)(((const DRAWITEMSTRUCT *)lpDrawItem)->CtlID),(LPARAM)(const DRAWITEMSTRUCT *)(lpDrawItem))
#define HANDLE_WM_MEASUREITEM(hwnd,wParam,lParam,fn) ((fn)((hwnd),(MEASUREITEMSTRUCT *)(lParam)),0L)
#define FORWARD_WM_MEASUREITEM(hwnd,lpMeasureItem,fn) (fn)((hwnd),WM_MEASUREITEM,(WPARAM)(((MEASUREITEMSTRUCT *)lpMeasureItem)->CtlID),(LPARAM)(MEASUREITEMSTRUCT *)(lpMeasureItem))
#define HANDLE_WM_CTLCOLORBTN(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HBRUSH)(fn)((hwnd),(HDC)(wParam),(HWND)(lParam),CTLCOLOR_BTN)
#define HANDLE_WM_CTLCOLOREDIT(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HBRUSH)(fn)((hwnd),(HDC)(wParam),(HWND)(lParam),CTLCOLOR_EDIT)
#define HANDLE_WM_CTLCOLORLISTBOX(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HBRUSH)(fn)((hwnd),(HDC)(wParam),(HWND)(lParam),CTLCOLOR_LISTBOX)
#define HANDLE_WM_CTLCOLORSTATIC(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HBRUSH)(fn)((hwnd),(HDC)(wParam),(HWND)(lParam),CTLCOLOR_STATIC)
#define HANDLE_WM_CTLCOLORDLG(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HBRUSH)(fn)((hwnd),(HDC)(wParam),(HWND)(lParam),CTLCOLOR_DLG)
#define HANDLE_WM_CTLCOLORSCROLLBAR(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HBRUSH)(fn)((hwnd),(HDC)(wParam),(HWND)(lParam),CTLCOLOR_SCROLLBAR)
#define HANDLE_WM_PARENTNOTIFY(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)LOWORD(wParam),(HWND)(lParam),(UINT)HIWORD(wParam)),0L)
#define FORWARD_WM_PARENTNOTIFY(hwnd,msg,hwndChild,idChild,fn) (fn)((hwnd),WM_PARENTNOTIFY,MAKEWPARAM(msg,idChild),(LPARAM)(hwndChild))
#define HANDLE_WM_NCHITTEST(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(UINT)(fn)((hwnd),(int)(short)LOWORD(lParam),(int)(short)HIWORD(lParam))
#define FORWARD_WM_NCHITTEST(hwnd,x,y,fn) (fn)((hwnd),WM_NCHITTEST,0L,MAKELPARAM((x),(y)))
#define HANDLE_WM_GETDLGCODE(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(UINT)(fn)(hwnd,(LPMSG)(lParam))
#define FORWARD_WM_GETDLGCODE(hwnd,lpmsg,fn) (fn)((hwnd),WM_GETDLGCODE,(WPARAM)(lpmsg?lpmsg->wParam:0),(LPARAM)(LPMSG)(lpmsg))
#define HANDLE_WM_QUERYDRAGICON(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(UINT_PTR)(fn)(hwnd)
#define FORWARD_WM_QUERYDRAGICON(hwnd,fn) (fn)((hwnd),WM_QUERYDRAGICON,0L,0L)
#define HANDLE_WM_SYSCOLORCHANGE(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_SYSCOLORCHANGE(hwnd,fn) (fn)((hwnd),WM_SYSCOLORCHANGE,0L,0L)
#define HANDLE_WM_FONTCHANGE(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_FONTCHANGE(hwnd,fn) (fn)((hwnd),WM_FONTCHANGE,0L,0L)
#define HANDLE_WM_TIMECHANGE(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_TIMECHANGE(hwnd,fn) (fn)((hwnd),WM_TIMECHANGE,0L,0L)
#define HANDLE_WM_SETTEXT(hwnd,wParam,lParam,fn) ((fn)((hwnd),(LPCTSTR)(lParam)),0L)
#define FORWARD_WM_SETTEXT(hwnd,lpszText,fn) (fn)((hwnd),WM_SETTEXT,0L,(LPARAM)(LPCTSTR)(lpszText))
#define HANDLE_WM_GETTEXT(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(int)(fn)((hwnd),(int)(wParam),(LPTSTR)(lParam))
#define FORWARD_WM_GETTEXT(hwnd,cchTextMax,lpszText,fn) (fn)((hwnd),WM_GETTEXT,(WPARAM)(int)(cchTextMax),(LPARAM)(LPTSTR)(lpszText))
#define HANDLE_WM_GETTEXTLENGTH(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(int)(fn)(hwnd)
#define FORWARD_WM_GETTEXTLENGTH(hwnd,fn) (fn)((hwnd),WM_GETTEXTLENGTH,0L,0L)
#define HANDLE_WM_DESTROYCLIPBOARD(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_DESTROYCLIPBOARD(hwnd,fn) (fn)((hwnd),WM_DESTROYCLIPBOARD,0L,0L)
#define HANDLE_WM_RENDERFORMAT(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HANDLE)(fn)((hwnd),(UINT)(wParam))
#define FORWARD_WM_RENDERFORMAT(hwnd,fmt,fn) (fn)((hwnd),WM_RENDERFORMAT,(WPARAM)(UINT)(fmt),0L)
#define HANDLE_WM_RENDERALLFORMATS(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_RENDERALLFORMATS(hwnd,fn) (fn)((hwnd),WM_RENDERALLFORMATS,0L,0L)
#define HANDLE_WM_DRAWCLIPBOARD(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_DRAWCLIPBOARD(hwnd,fn) (fn)((hwnd),WM_DRAWCLIPBOARD,0L,0L)
#define HANDLE_WM_CHANGECBCHAIN(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(wParam),(HWND)(lParam)),0L)
#define FORWARD_WM_CHANGECBCHAIN(hwnd,hwndRemove,hwndNext,fn) (fn)((hwnd),WM_CHANGECBCHAIN,(WPARAM)(HWND)(hwndRemove),(LPARAM)(HWND)(hwndNext))
#define HANDLE_WM_MDIACTIVATE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(BOOL)(lParam==(LPARAM)hwnd),(HWND)(lParam),(HWND)(wParam)),0L)
#define HANDLE_WM_ENTERIDLE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),(HWND)(lParam)),0L)
#define FORWARD_WM_ENTERIDLE(hwnd,source,hwndSource,fn) (fn)((hwnd),WM_ENTERIDLE,(WPARAM)(UINT)(source),(LPARAM)(HWND)(hwndSource))
#define HANDLE_WM_COMPAREITEM(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(int)(fn)((hwnd),(const COMPAREITEMSTRUCT *)(lParam))
#define FORWARD_WM_COMPAREITEM(hwnd,lpCompareItem,fn) (fn)((hwnd),WM_COMPAREITEM,(WPARAM)(((const COMPAREITEMSTRUCT *)(lpCompareItem))->CtlID),(LPARAM)(const COMPAREITEMSTRUCT *)(lpCompareItem))
#define HANDLE_WM_DELETEITEM(hwnd,wParam,lParam,fn) ((fn)((hwnd),(const DELETEITEMSTRUCT *)(lParam)),0L)
#define FORWARD_WM_DELETEITEM(hwnd,lpDeleteItem,fn) (fn)((hwnd),WM_DELETEITEM,(WPARAM)(((const DELETEITEMSTRUCT *)(lpDeleteItem))->CtlID),(LPARAM)(const DELETEITEMSTRUCT *)(lpDeleteItem))
#define HANDLE_WM_VKEYTOITEM(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(int)(fn)((hwnd),(UINT)LOWORD(wParam),(HWND)(lParam),(int)(short)HIWORD(wParam))
#define FORWARD_WM_VKEYTOITEM(hwnd,vk,hwndListbox,iCaret,fn) (fn)((hwnd),WM_VKEYTOITEM,MAKEWPARAM((vk),(iCaret)),(LPARAM)(hwndListbox))
#define HANDLE_WM_CHARTOITEM(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(int)(fn)((hwnd),(UINT)LOWORD(wParam),(HWND)(lParam),(int)(short)HIWORD(wParam))
#define FORWARD_WM_CHARTOITEM(hwnd,ch,hwndListbox,iCaret,fn) (fn)((hwnd),WM_CHARTOITEM,MAKEWPARAM((UINT)(ch),(UINT)(iCaret)),(LPARAM)(hwndListbox))
#define HANDLE_WM_WINDOWPOSCHANGING(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(BOOL)(fn)((hwnd),(LPWINDOWPOS)(lParam))
#define FORWARD_WM_WINDOWPOSCHANGING(hwnd,lpwpos,fn) (fn)((hwnd),WM_WINDOWPOSCHANGING,0L,(LPARAM)(LPWINDOWPOS)(lpwpos))
#define HANDLE_WM_WINDOWPOSCHANGED(hwnd,wParam,lParam,fn) ((fn)((hwnd),(const LPWINDOWPOS)(lParam)),0L)
#define FORWARD_WM_WINDOWPOSCHANGED(hwnd,lpwpos,fn) (fn)((hwnd),WM_WINDOWPOSCHANGED,0L,(LPARAM)(const LPWINDOWPOS)(lpwpos))
#define HANDLE_WM_NCPAINT(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HRGN)(wParam)),0L)
#define FORWARD_WM_NCPAINT(hwnd,hrgn,fn) (fn)((hwnd),WM_NCPAINT,(WPARAM)(HRGN)(hrgn),0L)
#define HANDLE_WM_NCACTIVATE(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(BOOL)(fn)((hwnd),(BOOL)(wParam),0L,0L)
#define FORWARD_WM_NCACTIVATE(hwnd,fActive,hwndActDeact,fMinimized,fn) (fn)((hwnd),WM_NCACTIVATE,(WPARAM)(BOOL)(fActive),0L)
#define HANDLE_WM_DROPFILES(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HDROP)(wParam)),0L)
#define FORWARD_WM_DROPFILES(hwnd,hdrop,fn) (fn)((hwnd),WM_DROPFILES,(WPARAM)(HDROP)(hdrop),0L)
#define HANDLE_WM_PALETTECHANGED(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(wParam)),0L)
#define FORWARD_WM_PALETTECHANGED(hwnd,hwndPaletteChange,fn) (fn)((hwnd),WM_PALETTECHANGED,(WPARAM)(HWND)(hwndPaletteChange),0L)
#define HANDLE_WM_QUERYNEWPALETTE(hwnd,wParam,lParam,fn) MAKELRESULT((BOOL)(fn)(hwnd),0L)
#define FORWARD_WM_QUERYNEWPALETTE(hwnd,fn) (fn)((hwnd),WM_QUERYNEWPALETTE,0L,0L)
#define HANDLE_WM_CANCELMODE(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_CANCELMODE(hwnd,fn) (fn)((hwnd),WM_CANCELMODE,0L,0L)
#define HANDLE_WM_CLEAR(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_CLEAR(hwnd,fn) (fn)((hwnd),WM_CLEAR,0L,0L)
#define HANDLE_WM_COPY(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_COPY(hwnd,fn) (fn)((hwnd),WM_COPY,0L,0L)
#define HANDLE_WM_CUT(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_CUT(hwnd,fn) (fn)((hwnd),WM_CUT,0L,0L)
#define HANDLE_WM_PASTE(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_PASTE(hwnd,fn) (fn)((hwnd),WM_PASTE,0L,0L)
#define HANDLE_WM_UNDO(hwnd,wParam,lParam,fn) ((fn)(hwnd),0L)
#define FORWARD_WM_UNDO(hwnd,fn) (fn)((hwnd),WM_UNDO,0L,0L)
#define FORWARD_WM_KEYDOWN(hwnd,vk,cRepeat,flags,fn) (fn)((hwnd),WM_KEYDOWN,(WPARAM)(UINT)(vk),MAKELPARAM((cRepeat),(flags)))
#define FORWARD_WM_KEYUP(hwnd,vk,cRepeat,flags,fn) (fn)((hwnd),WM_KEYUP,(WPARAM)(UINT)(vk),MAKELPARAM((cRepeat),(flags)))
#define FORWARD_WM_SYSKEYDOWN(hwnd,vk,cRepeat,flags,fn) (fn)((hwnd),WM_SYSKEYDOWN,(WPARAM)(UINT)(vk),MAKELPARAM((cRepeat),(flags)))
#define FORWARD_WM_SYSKEYUP(hwnd,vk,cRepeat,flags,fn) (fn)((hwnd),WM_SYSKEYUP,(WPARAM)(UINT)(vk),MAKELPARAM((cRepeat),(flags)))
#define FORWARD_WM_LBUTTONDOWN(hwnd,fDoubleClick,x,y,keyFlags,fn) (fn)((hwnd),(fDoubleClick)?WM_LBUTTONDBLCLK:WM_LBUTTONDOWN,(WPARAM)(UINT)(keyFlags),MAKELPARAM((x),(y)))
#define FORWARD_WM_RBUTTONDOWN(hwnd,fDoubleClick,x,y,keyFlags,fn) (fn)((hwnd),(fDoubleClick)?WM_RBUTTONDBLCLK:WM_RBUTTONDOWN,(WPARAM)(UINT)(keyFlags),MAKELPARAM((x),(y)))
#define FORWARD_WM_MBUTTONDOWN(hwnd,fDoubleClick,x,y,keyFlags,fn) (fn)((hwnd),(fDoubleClick)?WM_MBUTTONDBLCLK:WM_MBUTTONDOWN,(WPARAM)(UINT)(keyFlags),MAKELPARAM((x),(y)))
#define FORWARD_WM_LBUTTONDBLCLK FORWARD_WM_LBUTTONDOWN
#define FORWARD_WM_RBUTTONDBLCLK FORWARD_WM_RBUTTONDOWN
#define FORWARD_WM_CTLCOLORBTN(hwnd,hdc,hwndChild,fn) (HBRUSH)(UINT_PTR)(fn)((hwnd),WM_CTLCOLORBTN,(WPARAM)(HDC)(hdc),(LPARAM)(HWND)(hwndChild))
#define FORWARD_WM_CTLCOLOREDIT(hwnd,hdc,hwndChild,fn) (HBRUSH)(UINT_PTR)(fn)((hwnd),WM_CTLCOLOREDIT,(WPARAM)(HDC)(hdc),(LPARAM)(HWND)(hwndChild))
#define FORWARD_WM_CTLCOLORLISTBOX(hwnd,hdc,hwndChild,fn) (HBRUSH)(UINT_PTR)(fn)((hwnd),WM_CTLCOLORLISTBOX,(WPARAM)(HDC)(hdc),(LPARAM)(HWND)(hwndChild))
#define FORWARD_WM_CTLCOLORSTATIC(hwnd,hdc,hwndChild,fn) (HBRUSH)(UINT_PTR)(fn)((hwnd),WM_CTLCOLORSTATIC,(WPARAM)(HDC)(hdc),(LPARAM)(HWND)(hwndChild))
#define FORWARD_WM_CTLCOLORDLG(hwnd,hdc,hwndChild,fn) (HBRUSH)(UINT_PTR)(fn)((hwnd),WM_CTLCOLORDLG,(WPARAM)(HDC)(hdc),(LPARAM)(HWND)(hwndChild))
#define FORWARD_WM_CTLCOLORSCROLLBAR(hwnd,hdc,hwndChild,fn) (HBRUSH)(UINT_PTR)(fn)((hwnd),WM_CTLCOLORSCROLLBAR,(WPARAM)(HDC)(hdc),(LPARAM)(HWND)(hwndChild))
#define FORWARD_WM_MENUSELECT(hwnd,hmenu,item,hmenuPopup,flags,fn) (fn)((hwnd),WM_MENUSELECT,MAKEWPARAM((item),(flags)),(LPARAM)(HMENU)((hmenu)?(hmenu):(hmenuPopup)))
#define FORWARD_WM_MDIACTIVATE(hwnd,fActive,hwndActivate,hwndDeactivate,fn) (fn)((hwnd),WM_MDIACTIVATE,(WPARAM)(hwndDeactivate),(LPARAM)(hwndActivate))

/* Unpacking that works with either packing (Windows 3.0's under WIN16_MESSAGES). */
#ifdef WIN16_MESSAGES
#define GET_WM_ACTIVATE_STATE(wp,lp) (wp)
#define GET_WM_ACTIVATE_FMINIMIZED(wp,lp) (BOOL)HIWORD(lp)
#define GET_WM_ACTIVATE_HWND(wp,lp) (HWND)(UINT_PTR)LOWORD(lp)
#define GET_WM_ACTIVATE_MPS(s,fmin,hwnd) (WPARAM)(s),MAKELONG((UINT_PTR)(hwnd),(fmin))
#define GET_WM_CHARTOITEM_CHAR(wp,lp) (TCHAR)(wp)
#define GET_WM_CHARTOITEM_POS(wp,lp) HIWORD(lp)
#define GET_WM_CHARTOITEM_HWND(wp,lp) (HWND)(UINT_PTR)LOWORD(lp)
#define GET_WM_COMMAND_ID(wp,lp) (int)(wp)
#define GET_WM_COMMAND_HWND(wp,lp) (HWND)(UINT_PTR)LOWORD(lp)
#define GET_WM_COMMAND_CMD(wp,lp) HIWORD(lp)
#define GET_WM_COMMAND_MPS(id,hwnd,cmd) (WPARAM)(id),MAKELONG((UINT_PTR)(hwnd),(cmd))
#define GET_WM_CTLCOLOR_HDC(wp,lp,msg) (HDC)(wp)
#define GET_WM_CTLCOLOR_HWND(wp,lp,msg) (HWND)(UINT_PTR)LOWORD(lp)
#define GET_WM_CTLCOLOR_TYPE(wp,lp,msg) HIWORD(lp)
#define GET_WM_MENUSELECT_CMD(wp,lp) (wp)
#define GET_WM_MENUSELECT_FLAGS(wp,lp) (UINT)LOWORD(lp)
#define GET_WM_MENUSELECT_HMENU(wp,lp) (HMENU)(UINT_PTR)HIWORD(lp)
#define GET_WM_MDIACTIVATE_FACTIVATE(hwnd,wp,lp) (BOOL)(wp)
#define GET_WM_MDIACTIVATE_HWNDDEACT(wp,lp) (HWND)(UINT_PTR)HIWORD(lp)
#define GET_WM_MDIACTIVATE_HWNDACTIVATE(wp,lp) (HWND)(UINT_PTR)LOWORD(lp)
#define GET_WM_PARENTNOTIFY_MSG(wp,lp) (wp)
#define GET_WM_PARENTNOTIFY_ID(wp,lp) HIWORD(lp)
#define GET_WM_PARENTNOTIFY_HWNDCHILD(wp,lp) (HWND)(UINT_PTR)LOWORD(lp)
#define GET_WM_VKEYTOITEM_CODE(wp,lp) (wp)
#define GET_WM_VKEYTOITEM_ITEM(wp,lp) HIWORD(lp)
#define GET_WM_VKEYTOITEM_HWND(wp,lp) (HWND)(UINT_PTR)LOWORD(lp)
#define GET_WM_HSCROLL_CODE(wp,lp) (wp)
#define GET_WM_HSCROLL_POS(wp,lp) LOWORD(lp)
#define GET_WM_HSCROLL_HWND(wp,lp) (HWND)(UINT_PTR)HIWORD(lp)
#define GET_WM_HSCROLL_MPS(code,pos,hwnd) (WPARAM)(code),MAKELONG((pos),(UINT_PTR)(hwnd))
#define GET_WM_VSCROLL_CODE(wp,lp) (wp)
#define GET_WM_VSCROLL_POS(wp,lp) LOWORD(lp)
#define GET_WM_VSCROLL_HWND(wp,lp) (HWND)(UINT_PTR)HIWORD(lp)
#define GET_WM_VSCROLL_MPS(code,pos,hwnd) (WPARAM)(code),MAKELONG((pos),(UINT_PTR)(hwnd))
#define GET_EM_SETSEL_START(wp,lp) LOWORD(lp)
#define GET_EM_SETSEL_END(wp,lp) HIWORD(lp)
#define GET_EM_SETSEL_MPS(start,end) 0,MAKELONG((start),(end))
#else
#define GET_WM_ACTIVATE_STATE(wp,lp) LOWORD(wp)
#define GET_WM_ACTIVATE_FMINIMIZED(wp,lp) (BOOL)HIWORD(wp)
#define GET_WM_ACTIVATE_HWND(wp,lp) (HWND)(lp)
#define GET_WM_ACTIVATE_MPS(s,fmin,hwnd) (WPARAM)MAKELONG((s),(fmin)),(LPARAM)(hwnd)
#define GET_WM_CHARTOITEM_CHAR(wp,lp) (TCHAR)LOWORD(wp)
#define GET_WM_CHARTOITEM_POS(wp,lp) HIWORD(wp)
#define GET_WM_CHARTOITEM_HWND(wp,lp) (HWND)(lp)
#define GET_WM_COMMAND_ID(wp,lp) LOWORD(wp)
#define GET_WM_COMMAND_HWND(wp,lp) (HWND)(lp)
#define GET_WM_COMMAND_CMD(wp,lp) HIWORD(wp)
#define GET_WM_COMMAND_MPS(id,hwnd,cmd) (WPARAM)MAKELONG((id),(cmd)),(LPARAM)(hwnd)
#define GET_WM_CTLCOLOR_HDC(wp,lp,msg) (HDC)(wp)
#define GET_WM_CTLCOLOR_HWND(wp,lp,msg) (HWND)(lp)
#define GET_WM_CTLCOLOR_TYPE(wp,lp,msg) (WORD)((msg)-WM_CTLCOLORMSGBOX)
#define GET_WM_MENUSELECT_CMD(wp,lp) LOWORD(wp)
#define GET_WM_MENUSELECT_FLAGS(wp,lp) (UINT)(int)(short)HIWORD(wp)
#define GET_WM_MENUSELECT_HMENU(wp,lp) (HMENU)(lp)
#define GET_WM_MDIACTIVATE_FACTIVATE(hwnd,wp,lp) ((lp)==(LPARAM)(hwnd))
#define GET_WM_MDIACTIVATE_HWNDDEACT(wp,lp) (HWND)(wp)
#define GET_WM_MDIACTIVATE_HWNDACTIVATE(wp,lp) (HWND)(lp)
#define GET_WM_PARENTNOTIFY_MSG(wp,lp) LOWORD(wp)
#define GET_WM_PARENTNOTIFY_ID(wp,lp) HIWORD(wp)
#define GET_WM_PARENTNOTIFY_HWNDCHILD(wp,lp) (HWND)(lp)
#define GET_WM_VKEYTOITEM_CODE(wp,lp) (int)LOWORD(wp)
#define GET_WM_VKEYTOITEM_ITEM(wp,lp) HIWORD(wp)
#define GET_WM_VKEYTOITEM_HWND(wp,lp) (HWND)(lp)
#define GET_WM_HSCROLL_CODE(wp,lp) LOWORD(wp)
#define GET_WM_HSCROLL_POS(wp,lp) HIWORD(wp)
#define GET_WM_HSCROLL_HWND(wp,lp) (HWND)(lp)
#define GET_WM_HSCROLL_MPS(code,pos,hwnd) (WPARAM)MAKELONG((code),(pos)),(LPARAM)(hwnd)
#define GET_WM_VSCROLL_CODE(wp,lp) LOWORD(wp)
#define GET_WM_VSCROLL_POS(wp,lp) HIWORD(wp)
#define GET_WM_VSCROLL_HWND(wp,lp) (HWND)(lp)
#define GET_WM_VSCROLL_MPS(code,pos,hwnd) (WPARAM)MAKELONG((code),(pos)),(LPARAM)(hwnd)
#define GET_EM_SETSEL_START(wp,lp) (INT)(wp)
#define GET_EM_SETSEL_END(wp,lp) (lp)
#define GET_EM_SETSEL_MPS(start,end) (WPARAM)(start),(LPARAM)(end)
#endif

/* Windows, GDI objects and memory. */
#define GetWindowInstance(hwnd) ((HINSTANCE)GetWindowLongPtr((hwnd),GWLP_HINSTANCE))
#define GetWindowStyle(hwnd) ((DWORD)GetWindowLong((hwnd),GWL_STYLE))
#define GetWindowExStyle(hwnd) ((DWORD)GetWindowLong((hwnd),GWL_EXSTYLE))
#define GetWindowOwner(hwnd) GetWindow((hwnd),GW_OWNER)
#define GetFirstChild(hwnd) GetTopWindow(hwnd)
#define GetFirstSibling(hwnd) GetWindow((hwnd),GW_HWNDFIRST)
#define GetLastSibling(hwnd) GetWindow((hwnd),GW_HWNDLAST)
#define GetNextSibling(hwnd) GetWindow((hwnd),GW_HWNDNEXT)
#define GetPrevSibling(hwnd) GetWindow((hwnd),GW_HWNDPREV)
#define GetWindowID(hwnd) GetDlgCtrlID(hwnd)
#define SetWindowRedraw(hwnd,fRedraw) ((void)SendMessage((hwnd),WM_SETREDRAW,(WPARAM)(BOOL)(fRedraw),0L))
#define SubclassWindow(hwnd,lpfn) ((WNDPROC)SetWindowLongPtr((hwnd),GWLP_WNDPROC,(LONG_PTR)(WNDPROC)(lpfn)))
#define IsMinimized(hwnd) IsIconic(hwnd)
#define IsMaximized(hwnd) IsZoomed(hwnd)
#define IsRestored(hwnd) ((GetWindowStyle(hwnd)&(WS_MINIMIZE|WS_MAXIMIZE))==0L)
#define SetWindowFont(hwnd,hfont,fRedraw) FORWARD_WM_SETFONT((hwnd),(hfont),(fRedraw),SendMessage)
#define GetWindowFont(hwnd) FORWARD_WM_GETFONT((hwnd),SendMessage)
#define MapWindowRect(hwndFrom,hwndTo,lprc) MapWindowPoints((hwndFrom),(hwndTo),(POINT *)(lprc),2)
#define DeletePen(hpen) DeleteObject((HGDIOBJ)(HPEN)(hpen))
#define SelectPen(hdc,hpen) ((HPEN)SelectObject((hdc),(HGDIOBJ)(HPEN)(hpen)))
#define GetStockPen(i) ((HPEN)GetStockObject(i))
#define DeleteBrush(hbr) DeleteObject((HGDIOBJ)(HBRUSH)(hbr))
#define SelectBrush(hdc,hbr) ((HBRUSH)SelectObject((hdc),(HGDIOBJ)(HBRUSH)(hbr)))
#define GetStockBrush(i) ((HBRUSH)GetStockObject(i))
#define DeleteRgn(hrgn) DeleteObject((HGDIOBJ)(HRGN)(hrgn))
#define DeletePalette(hpal) DeleteObject((HGDIOBJ)(HPALETTE)(hpal))
#define DeleteFont(hfont) DeleteObject((HGDIOBJ)(HFONT)(hfont))
#define SelectFont(hdc,hfont) ((HFONT)SelectObject((hdc),(HGDIOBJ)(HFONT)(hfont)))
#define GetStockFont(i) ((HFONT)GetStockObject(i))
#define DeleteBitmap(hbm) DeleteObject((HGDIOBJ)(HBITMAP)(hbm))
#define SelectBitmap(hdc,hbm) ((HBITMAP)SelectObject((hdc),(HGDIOBJ)(HBITMAP)(hbm)))
#define InsetRect(lprc,dx,dy) InflateRect((lprc),-(dx),-(dy))
#define GlobalPtrHandle(lp) ((HGLOBAL)GlobalHandle(lp))
#define GlobalLockPtr(lp) ((BOOL)GlobalLock(GlobalPtrHandle(lp)))
#define GlobalUnlockPtr(lp) GlobalUnlock(GlobalPtrHandle(lp))
#define GlobalAllocPtr(flags,cb) (GlobalLock(GlobalAlloc((flags),(cb))))
#define GlobalReAllocPtr(lp,cbNew,flags) (GlobalUnlockPtr(lp),GlobalLock(GlobalReAlloc(GlobalPtrHandle(lp),(cbNew),(flags))))
#define GlobalFreePtr(lp) (GlobalUnlockPtr(lp),(BOOL)(ULONG_PTR)GlobalFree(GlobalPtrHandle(lp)))

/* Controls. */
#define Static_Enable(hwnd,fEnable) EnableWindow((hwnd),(fEnable))
#define Static_GetText(hwnd,lpch,cchMax) GetWindowText((hwnd),(lpch),(cchMax))
#define Static_GetTextLength(hwnd) GetWindowTextLength(hwnd)
#define Static_SetText(hwnd,lpsz) SetWindowText((hwnd),(lpsz))
#define Static_SetIcon(hwnd,hIcon) ((HICON)(UINT_PTR)SendMessage((hwnd),STM_SETICON,(WPARAM)(HICON)(hIcon),0L))
#define Static_GetIcon(hwnd,hIcon) ((HICON)(UINT_PTR)SendMessage((hwnd),STM_GETICON,0L,0L))
#define Button_Enable(hwnd,fEnable) EnableWindow((hwnd),(fEnable))
#define Button_GetText(hwnd,lpch,cchMax) GetWindowText((hwnd),(lpch),(cchMax))
#define Button_GetTextLength(hwnd) GetWindowTextLength(hwnd)
#define Button_SetText(hwnd,lpsz) SetWindowText((hwnd),(lpsz))
#define Button_GetCheck(hwnd) ((int)(DWORD)SendMessage((hwnd),BM_GETCHECK,0L,0L))
#define Button_SetCheck(hwnd,check) ((void)SendMessage((hwnd),BM_SETCHECK,(WPARAM)(int)(check),0L))
#define Button_GetState(hwnd) ((int)(DWORD)SendMessage((hwnd),BM_GETSTATE,0L,0L))
#define Button_SetState(hwnd,state) ((UINT)(DWORD)SendMessage((hwnd),BM_SETSTATE,(WPARAM)(int)(state),0L))
#define Button_SetStyle(hwnd,style,fRedraw) ((void)SendMessage((hwnd),BM_SETSTYLE,(WPARAM)LOWORD(style),MAKELPARAM(((fRedraw)?TRUE:FALSE),0)))
#define Edit_Enable(hwnd,fEnable) EnableWindow((hwnd),(fEnable))
#define Edit_GetText(hwnd,lpch,cchMax) GetWindowText((hwnd),(lpch),(cchMax))
#define Edit_GetTextLength(hwnd) GetWindowTextLength(hwnd)
#define Edit_SetText(hwnd,lpsz) SetWindowText((hwnd),(lpsz))
#define Edit_LimitText(hwnd,cchMax) ((void)SendMessage((hwnd),EM_LIMITTEXT,(WPARAM)(cchMax),0L))
#define Edit_GetLineCount(hwnd) ((int)(DWORD)SendMessage((hwnd),EM_GETLINECOUNT,0L,0L))
#define Edit_GetLine(hwnd,line,lpch,cchMax) ((*((int *)(lpch))=(cchMax)),((int)(DWORD)SendMessage((hwnd),EM_GETLINE,(WPARAM)(int)(line),(LPARAM)(LPTSTR)(lpch))))
#define Edit_GetRect(hwnd,lprc) ((void)SendMessage((hwnd),EM_GETRECT,0L,(LPARAM)(RECT *)(lprc)))
#define Edit_SetRect(hwnd,lprc) ((void)SendMessage((hwnd),EM_SETRECT,0L,(LPARAM)(const RECT *)(lprc)))
#define Edit_SetRectNoPaint(hwnd,lprc) ((void)SendMessage((hwnd),EM_SETRECTNP,0L,(LPARAM)(const RECT *)(lprc)))
#define Edit_GetSel(hwnd) ((DWORD)SendMessage((hwnd),EM_GETSEL,0L,0L))
#define Edit_SetSel(hwnd,ichStart,ichEnd) ((void)SendMessage((hwnd),EM_SETSEL,GET_EM_SETSEL_MPS((ichStart),(ichEnd))))
#define Edit_ReplaceSel(hwnd,lpszReplace) ((void)SendMessage((hwnd),EM_REPLACESEL,0L,(LPARAM)(LPCTSTR)(lpszReplace)))
#define Edit_GetModify(hwnd) ((BOOL)(DWORD)SendMessage((hwnd),EM_GETMODIFY,0L,0L))
#define Edit_SetModify(hwnd,fModified) ((void)SendMessage((hwnd),EM_SETMODIFY,(WPARAM)(UINT)(fModified),0L))
#define Edit_LineFromChar(hwnd,ich) ((int)(DWORD)SendMessage((hwnd),EM_LINEFROMCHAR,(WPARAM)(int)(ich),0L))
#define Edit_LineIndex(hwnd,line) ((int)(DWORD)SendMessage((hwnd),EM_LINEINDEX,(WPARAM)(int)(line),0L))
#define Edit_LineLength(hwnd,line) ((int)(DWORD)SendMessage((hwnd),EM_LINELENGTH,(WPARAM)(int)(line),0L))
#define Edit_Scroll(hwnd,dv,dh) ((void)SendMessage((hwnd),EM_LINESCROLL,(WPARAM)(dh),(LPARAM)(dv)))
#define Edit_CanUndo(hwnd) ((BOOL)(DWORD)SendMessage((hwnd),EM_CANUNDO,0L,0L))
#define Edit_Undo(hwnd) ((BOOL)(DWORD)SendMessage((hwnd),EM_UNDO,0L,0L))
#define Edit_EmptyUndoBuffer(hwnd) ((void)SendMessage((hwnd),EM_EMPTYUNDOBUFFER,0L,0L))
#define Edit_SetPasswordChar(hwnd,ch) ((void)SendMessage((hwnd),EM_SETPASSWORDCHAR,(WPARAM)(UINT)(ch),0L))
#define Edit_SetTabStops(hwnd,cTabs,lpTabs) ((void)SendMessage((hwnd),EM_SETTABSTOPS,(WPARAM)(int)(cTabs),(LPARAM)(const int *)(lpTabs)))
#define Edit_FmtLines(hwnd,fAddEOL) ((BOOL)(DWORD)SendMessage((hwnd),EM_FMTLINES,(WPARAM)(BOOL)(fAddEOL),0L))
#define Edit_GetHandle(hwnd) ((HLOCAL)(UINT_PTR)SendMessage((hwnd),EM_GETHANDLE,0L,0L))
#define Edit_SetHandle(hwnd,h) ((void)SendMessage((hwnd),EM_SETHANDLE,(WPARAM)(UINT_PTR)(HLOCAL)(h),0L))
#define Edit_GetFirstVisibleLine(hwnd) ((int)(DWORD)SendMessage((hwnd),EM_GETFIRSTVISIBLELINE,0L,0L))
#define Edit_SetReadOnly(hwnd,fReadOnly) ((BOOL)(DWORD)SendMessage((hwnd),EM_SETREADONLY,(WPARAM)(BOOL)(fReadOnly),0L))
#define ScrollBar_Enable(hwnd,flags) EnableScrollBar((hwnd),SB_CTL,(flags))
#define ScrollBar_Show(hwnd,fShow) ShowWindow((hwnd),(fShow)?SW_SHOWNORMAL:SW_HIDE)
#define ScrollBar_SetPos(hwnd,pos,fRedraw) SetScrollPos((hwnd),SB_CTL,(pos),(fRedraw))
#define ScrollBar_GetPos(hwnd) GetScrollPos((hwnd),SB_CTL)
#define ScrollBar_SetRange(hwnd,posMin,posMax,fRedraw) SetScrollRange((hwnd),SB_CTL,(posMin),(posMax),(fRedraw))
#define ScrollBar_GetRange(hwnd,lpposMin,lpposMax) GetScrollRange((hwnd),SB_CTL,(lpposMin),(lpposMax))
#define ListBox_Enable(hwnd,fEnable) EnableWindow((hwnd),(fEnable))
#define ListBox_GetCount(hwnd) ((int)(DWORD)SendMessage((hwnd),LB_GETCOUNT,0L,0L))
#define ListBox_ResetContent(hwnd) ((BOOL)(DWORD)SendMessage((hwnd),LB_RESETCONTENT,0L,0L))
#define ListBox_AddString(hwnd,lpsz) ((int)(DWORD)SendMessage((hwnd),LB_ADDSTRING,0L,(LPARAM)(LPCTSTR)(lpsz)))
#define ListBox_InsertString(hwnd,index,lpsz) ((int)(DWORD)SendMessage((hwnd),LB_INSERTSTRING,(WPARAM)(int)(index),(LPARAM)(LPCTSTR)(lpsz)))
#define ListBox_AddItemData(hwnd,data) ((int)(DWORD)SendMessage((hwnd),LB_ADDSTRING,0L,(LPARAM)(data)))
#define ListBox_InsertItemData(hwnd,index,data) ((int)(DWORD)SendMessage((hwnd),LB_INSERTSTRING,(WPARAM)(int)(index),(LPARAM)(data)))
#define ListBox_DeleteString(hwnd,index) ((int)(DWORD)SendMessage((hwnd),LB_DELETESTRING,(WPARAM)(int)(index),0L))
#define ListBox_GetTextLen(hwnd,index) ((int)(DWORD)SendMessage((hwnd),LB_GETTEXTLEN,(WPARAM)(int)(index),0L))
#define ListBox_GetText(hwnd,index,lpszBuffer) ((int)(DWORD)SendMessage((hwnd),LB_GETTEXT,(WPARAM)(int)(index),(LPARAM)(LPCTSTR)(lpszBuffer)))
#define ListBox_GetItemData(hwnd,index) ((LRESULT)(ULONG_PTR)SendMessage((hwnd),LB_GETITEMDATA,(WPARAM)(int)(index),0L))
#define ListBox_SetItemData(hwnd,index,data) ((int)(DWORD)SendMessage((hwnd),LB_SETITEMDATA,(WPARAM)(int)(index),(LPARAM)(data)))
#define ListBox_FindString(hwnd,indexStart,lpszFind) ((int)(DWORD)SendMessage((hwnd),LB_FINDSTRING,(WPARAM)(int)(indexStart),(LPARAM)(LPCTSTR)(lpszFind)))
#define ListBox_FindItemData(hwnd,indexStart,data) ((int)(DWORD)SendMessage((hwnd),LB_FINDSTRING,(WPARAM)(int)(indexStart),(LPARAM)(data)))
#define ListBox_SetSel(hwnd,fSelect,index) ((int)(DWORD)SendMessage((hwnd),LB_SETSEL,(WPARAM)(BOOL)(fSelect),(LPARAM)(index)))
#define ListBox_SelItemRange(hwnd,fSelect,first,last) ((int)(DWORD)SendMessage((hwnd),LB_SELITEMRANGE,(WPARAM)(BOOL)(fSelect),MAKELPARAM((first),(last))))
#define ListBox_GetCurSel(hwnd) ((int)(DWORD)SendMessage((hwnd),LB_GETCURSEL,0L,0L))
#define ListBox_SetCurSel(hwnd,index) ((int)(DWORD)SendMessage((hwnd),LB_SETCURSEL,(WPARAM)(int)(index),0L))
#define ListBox_SelectString(hwnd,indexStart,lpszFind) ((int)(DWORD)SendMessage((hwnd),LB_SELECTSTRING,(WPARAM)(int)(indexStart),(LPARAM)(LPCTSTR)(lpszFind)))
#define ListBox_GetSel(hwnd,index) ((int)(DWORD)SendMessage((hwnd),LB_GETSEL,(WPARAM)(int)(index),0L))
#define ListBox_GetSelCount(hwnd) ((int)(DWORD)SendMessage((hwnd),LB_GETSELCOUNT,0L,0L))
#define ListBox_GetTopIndex(hwnd) ((int)(DWORD)SendMessage((hwnd),LB_GETTOPINDEX,0L,0L))
#define ListBox_GetSelItems(hwnd,cItems,lpItems) ((int)(DWORD)SendMessage((hwnd),LB_GETSELITEMS,(WPARAM)(int)(cItems),(LPARAM)(int *)(lpItems)))
#define ListBox_SetTopIndex(hwnd,indexTop) ((int)(DWORD)SendMessage((hwnd),LB_SETTOPINDEX,(WPARAM)(int)(indexTop),0L))
#define ListBox_SetColumnWidth(hwnd,cxColumn) ((void)SendMessage((hwnd),LB_SETCOLUMNWIDTH,(WPARAM)(int)(cxColumn),0L))
#define ListBox_SetTabStops(hwnd,cTabs,lpTabs) ((BOOL)(DWORD)SendMessage((hwnd),LB_SETTABSTOPS,(WPARAM)(int)(cTabs),(LPARAM)(int *)(lpTabs)))
#define ListBox_GetItemRect(hwnd,index,lprc) ((int)(DWORD)SendMessage((hwnd),LB_GETITEMRECT,(WPARAM)(int)(index),(LPARAM)(RECT *)(lprc)))
#define ListBox_SetCaretIndex(hwnd,index) ((int)(DWORD)SendMessage((hwnd),LB_SETCARETINDEX,(WPARAM)(int)(index),0L))
#define ListBox_GetCaretIndex(hwnd) ((int)(DWORD)SendMessage((hwnd),LB_GETCARETINDEX,0L,0L))
#define ListBox_SetItemHeight(hwnd,index,cy) ((int)(DWORD)SendMessage((hwnd),LB_SETITEMHEIGHT,(WPARAM)(int)(index),MAKELPARAM((cy),0)))
#define ListBox_GetItemHeight(hwnd,index) ((int)(DWORD)SendMessage((hwnd),LB_GETITEMHEIGHT,(WPARAM)(int)(index),0L))
#define ListBox_Dir(hwnd,attrs,lpszFileSpec) ((int)(DWORD)SendMessage((hwnd),LB_DIR,(WPARAM)(UINT)(attrs),(LPARAM)(LPCTSTR)(lpszFileSpec)))
#define ComboBox_Enable(hwnd,fEnable) EnableWindow((hwnd),(fEnable))
#define ComboBox_GetText(hwnd,lpch,cchMax) GetWindowText((hwnd),(lpch),(cchMax))
#define ComboBox_GetTextLength(hwnd) GetWindowTextLength(hwnd)
#define ComboBox_SetText(hwnd,lpsz) SetWindowText((hwnd),(lpsz))
#define ComboBox_LimitText(hwnd,cchLimit) ((int)(DWORD)SendMessage((hwnd),CB_LIMITTEXT,(WPARAM)(int)(cchLimit),0L))
#define ComboBox_GetEditSel(hwnd) ((DWORD)SendMessage((hwnd),CB_GETEDITSEL,0L,0L))
#define ComboBox_SetEditSel(hwnd,ichStart,ichEnd) ((int)(DWORD)SendMessage((hwnd),CB_SETEDITSEL,0L,MAKELPARAM((ichStart),(ichEnd))))
#define ComboBox_GetCount(hwnd) ((int)(DWORD)SendMessage((hwnd),CB_GETCOUNT,0L,0L))
#define ComboBox_ResetContent(hwnd) ((int)(DWORD)SendMessage((hwnd),CB_RESETCONTENT,0L,0L))
#define ComboBox_AddString(hwnd,lpsz) ((int)(DWORD)SendMessage((hwnd),CB_ADDSTRING,0L,(LPARAM)(LPCTSTR)(lpsz)))
#define ComboBox_InsertString(hwnd,index,lpsz) ((int)(DWORD)SendMessage((hwnd),CB_INSERTSTRING,(WPARAM)(int)(index),(LPARAM)(LPCTSTR)(lpsz)))
#define ComboBox_AddItemData(hwnd,data) ((int)(DWORD)SendMessage((hwnd),CB_ADDSTRING,0L,(LPARAM)(data)))
#define ComboBox_InsertItemData(hwnd,index,data) ((int)(DWORD)SendMessage((hwnd),CB_INSERTSTRING,(WPARAM)(int)(index),(LPARAM)(data)))
#define ComboBox_DeleteString(hwnd,index) ((int)(DWORD)SendMessage((hwnd),CB_DELETESTRING,(WPARAM)(int)(index),0L))
#define ComboBox_GetLBTextLen(hwnd,index) ((int)(DWORD)SendMessage((hwnd),CB_GETLBTEXTLEN,(WPARAM)(int)(index),0L))
#define ComboBox_GetLBText(hwnd,index,lpszBuffer) ((int)(DWORD)SendMessage((hwnd),CB_GETLBTEXT,(WPARAM)(int)(index),(LPARAM)(LPCTSTR)(lpszBuffer)))
#define ComboBox_GetItemData(hwnd,index) ((LRESULT)(ULONG_PTR)SendMessage((hwnd),CB_GETITEMDATA,(WPARAM)(int)(index),0L))
#define ComboBox_SetItemData(hwnd,index,data) ((int)(DWORD)SendMessage((hwnd),CB_SETITEMDATA,(WPARAM)(int)(index),(LPARAM)(data)))
#define ComboBox_FindString(hwnd,indexStart,lpszFind) ((int)(DWORD)SendMessage((hwnd),CB_FINDSTRING,(WPARAM)(int)(indexStart),(LPARAM)(LPCTSTR)(lpszFind)))
#define ComboBox_FindItemData(hwnd,indexStart,data) ((int)(DWORD)SendMessage((hwnd),CB_FINDSTRING,(WPARAM)(int)(indexStart),(LPARAM)(data)))
#define ComboBox_GetCurSel(hwnd) ((int)(DWORD)SendMessage((hwnd),CB_GETCURSEL,0L,0L))
#define ComboBox_SetCurSel(hwnd,index) ((int)(DWORD)SendMessage((hwnd),CB_SETCURSEL,(WPARAM)(int)(index),0L))
#define ComboBox_SelectString(hwnd,indexStart,lpszSelect) ((int)(DWORD)SendMessage((hwnd),CB_SELECTSTRING,(WPARAM)(int)(indexStart),(LPARAM)(LPCTSTR)(lpszSelect)))
#define ComboBox_SelectItemData(hwnd,indexStart,data) ((int)(DWORD)SendMessage((hwnd),CB_SELECTSTRING,(WPARAM)(int)(indexStart),(LPARAM)(data)))
#define ComboBox_Dir(hwnd,attrs,lpszFileSpec) ((int)(DWORD)SendMessage((hwnd),CB_DIR,(WPARAM)(UINT)(attrs),(LPARAM)(LPCTSTR)(lpszFileSpec)))
#define ComboBox_ShowDropdown(hwnd,fShow) ((BOOL)(DWORD)SendMessage((hwnd),CB_SHOWDROPDOWN,(WPARAM)(BOOL)(fShow),0L))
#define ComboBox_GetDroppedState(hwnd) ((BOOL)(DWORD)SendMessage((hwnd),CB_GETDROPPEDSTATE,0L,0L))
#define ComboBox_GetDroppedControlRect(hwnd,lprc) ((void)SendMessage((hwnd),CB_GETDROPPEDCONTROLRECT,0L,(LPARAM)(RECT *)(lprc)))
#define ComboBox_GetItemHeight(hwnd) ((int)(DWORD)SendMessage((hwnd),CB_GETITEMHEIGHT,0L,0L))
#define ComboBox_SetItemHeight(hwnd,index,cyItem) ((int)(DWORD)SendMessage((hwnd),CB_SETITEMHEIGHT,(WPARAM)(int)(index),(LPARAM)(int)(cyItem)))
#define ComboBox_GetExtendedUI(hwnd) ((UINT)(DWORD)SendMessage((hwnd),CB_GETEXTENDEDUI,0L,0L))
#define ComboBox_SetExtendedUI(hwnd,flags) ((int)(DWORD)SendMessage((hwnd),CB_SETEXTENDEDUI,(WPARAM)(UINT)(flags),0L))
/* Windows 3.0's packing (WIN16_MESSAGES) for the messages it packs otherwise:
 * a handle in lParam beside wParam's second WORD, one WM_CTLCOLOR. */
#ifdef WIN16_MESSAGES
#undef HANDLE_WM_ACTIVATE
#undef FORWARD_WM_ACTIVATE
#define HANDLE_WM_ACTIVATE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),(HWND)(UINT_PTR)LOWORD(lParam),(BOOL)HIWORD(lParam)),0L)
#define FORWARD_WM_ACTIVATE(hwnd,state,hwndActDeact,fMinimized,fn) (fn)((hwnd),WM_ACTIVATE,(WPARAM)(state),MAKELPARAM((UINT_PTR)(hwndActDeact),(fMinimized)))
#undef HANDLE_WM_HSCROLL
#undef FORWARD_WM_HSCROLL
#undef HANDLE_WM_VSCROLL
#undef FORWARD_WM_VSCROLL
#define HANDLE_WM_HSCROLL(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(UINT_PTR)HIWORD(lParam),(UINT)(wParam),(int)(short)LOWORD(lParam)),0L)
#define FORWARD_WM_HSCROLL(hwnd,hwndCtl,code,pos,fn) (fn)((hwnd),WM_HSCROLL,(WPARAM)(code),MAKELPARAM((pos),(UINT_PTR)(hwndCtl)))
#define HANDLE_WM_VSCROLL(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HWND)(UINT_PTR)HIWORD(lParam),(UINT)(wParam),(int)(short)LOWORD(lParam)),0L)
#define FORWARD_WM_VSCROLL(hwnd,hwndCtl,code,pos,fn) (fn)((hwnd),WM_VSCROLL,(WPARAM)(code),MAKELPARAM((pos),(UINT_PTR)(hwndCtl)))
#undef HANDLE_WM_MENUSELECT
#undef FORWARD_WM_MENUSELECT
#define HANDLE_WM_MENUSELECT(hwnd,wParam,lParam,fn) ((fn)((hwnd),(HMENU)(UINT_PTR)HIWORD(lParam),(LOWORD(lParam)&MF_POPUP)?0:(int)(wParam),(LOWORD(lParam)&MF_POPUP)?(HMENU)(UINT_PTR)(wParam):0,(UINT)(((short)LOWORD(lParam)==-1)?0xFFFFFFFF:LOWORD(lParam))),0L)
#define FORWARD_WM_MENUSELECT(hwnd,hmenu,item,hmenuPopup,flags,fn) (fn)((hwnd),WM_MENUSELECT,((flags)&MF_POPUP)?(WPARAM)(UINT_PTR)(hmenuPopup):(WPARAM)(item),MAKELPARAM((flags),(UINT_PTR)(hmenu)))
#undef HANDLE_WM_MENUCHAR
#undef FORWARD_WM_MENUCHAR
#define HANDLE_WM_MENUCHAR(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(fn)((hwnd),(UINT)(wParam),(UINT)LOWORD(lParam),(HMENU)(UINT_PTR)HIWORD(lParam))
#define FORWARD_WM_MENUCHAR(hwnd,ch,flags,hmenu,fn) (fn)((hwnd),WM_MENUCHAR,(WPARAM)(ch),MAKELPARAM((flags),(UINT_PTR)(hmenu)))
#undef HANDLE_WM_COMMAND
#undef FORWARD_WM_COMMAND
#define HANDLE_WM_COMMAND(hwnd,wParam,lParam,fn) ((fn)((hwnd),(int)(wParam),(HWND)(UINT_PTR)LOWORD(lParam),(UINT)HIWORD(lParam)),0L)
#define FORWARD_WM_COMMAND(hwnd,id,hwndCtl,codeNotify,fn) (fn)((hwnd),WM_COMMAND,(WPARAM)(id),MAKELPARAM((UINT_PTR)(hwndCtl),(codeNotify)))
#define HANDLE_WM_CTLCOLOR(hwnd,wParam,lParam,fn) (LRESULT)(UINT_PTR)(HBRUSH)(fn)((hwnd),(HDC)(wParam),(HWND)(UINT_PTR)LOWORD(lParam),(int)HIWORD(lParam))
#define FORWARD_WM_CTLCOLOR(hwnd,hdc,hwndChild,type,fn) (HBRUSH)(UINT_PTR)(fn)((hwnd),WM_CTLCOLOR,(WPARAM)(hdc),MAKELPARAM((UINT_PTR)(hwndChild),(type)))
#undef HANDLE_WM_PARENTNOTIFY
#undef FORWARD_WM_PARENTNOTIFY
#define HANDLE_WM_PARENTNOTIFY(hwnd,wParam,lParam,fn) ((fn)((hwnd),(UINT)(wParam),(HWND)(UINT_PTR)LOWORD(lParam),(UINT)HIWORD(lParam)),0L)
#define FORWARD_WM_PARENTNOTIFY(hwnd,msg,hwndChild,idChild,fn) (fn)((hwnd),WM_PARENTNOTIFY,(WPARAM)(msg),MAKELPARAM((UINT_PTR)(hwndChild),(idChild)))
#undef HANDLE_WM_MDIACTIVATE
#undef FORWARD_WM_MDIACTIVATE
#define HANDLE_WM_MDIACTIVATE(hwnd,wParam,lParam,fn) ((fn)((hwnd),(BOOL)(wParam),(HWND)(UINT_PTR)LOWORD(lParam),(HWND)(UINT_PTR)HIWORD(lParam)),0L)
#define FORWARD_WM_MDIACTIVATE(hwnd,fActive,hwndActivate,hwndDeactivate,fn) (fn)((hwnd),WM_MDIACTIVATE,(WPARAM)(fActive),MAKELPARAM((UINT_PTR)(hwndActivate),(UINT_PTR)(hwndDeactivate)))
#undef HANDLE_WM_VKEYTOITEM
#undef FORWARD_WM_VKEYTOITEM
#undef HANDLE_WM_CHARTOITEM
#undef FORWARD_WM_CHARTOITEM
#define HANDLE_WM_VKEYTOITEM(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(int)(fn)((hwnd),(UINT)(wParam),(HWND)(UINT_PTR)LOWORD(lParam),(int)(short)HIWORD(lParam))
#define FORWARD_WM_VKEYTOITEM(hwnd,vk,hwndListbox,iCaret,fn) (fn)((hwnd),WM_VKEYTOITEM,(WPARAM)(vk),MAKELPARAM((UINT_PTR)(hwndListbox),(iCaret)))
#define HANDLE_WM_CHARTOITEM(hwnd,wParam,lParam,fn) (LRESULT)(DWORD)(int)(fn)((hwnd),(UINT)(wParam),(HWND)(UINT_PTR)LOWORD(lParam),(int)(short)HIWORD(lParam))
#define FORWARD_WM_CHARTOITEM(hwnd,ch,hwndListbox,iCaret,fn) (fn)((hwnd),WM_CHARTOITEM,(WPARAM)(ch),MAKELPARAM((UINT_PTR)(hwndListbox),(iCaret)))
#endif

#endif
