/* SPDX-License-Identifier: GPL-2.0-or-later
 * Shared behavioral cases run against the host kernel and native IA-64 ABI.
 * The includer supplies FCB_CHECK and FCB_CALL.
 */
static int fcb_test_call(unsigned fn,void *f,u32 *records,unsigned status) {
    DosRegs r={.ax=fn<<8,.dx=(uintptr_t)f,.cx=records?*records:0};
    FCB_CHECK(!FCB_CALL(&r));
    if((r.ax&255)!=status) FCB_DIAGNOSTIC(fn,status,(unsigned)r.ax,(unsigned)r.bx);
    FCB_CHECK((r.ax&255)==status);
    if(records) *records=r.cx;
    return r.bx;
}
static int fcb_test_name(DosFcb *f,const char *name) {
    memset(f,0,sizeof(*f));
    DosRegs r={.ax=0x2900,.si=(uintptr_t)name,.di=(uintptr_t)f};
    FCB_CHECK(!FCB_CALL(&r) && r.ax<2 && !r.bx && !*(const char *)(uintptr_t)r.si); return 0;
}
static int fcb_test_dta(void *data,u32 size) {
    DosRegs r={.ax=0x1a01,.dx=(uintptr_t)data,.cx=size}; FCB_CHECK(!FCB_CALL(&r)); return 0;
}
static int fcb_test_suite(void) {
    char cwd[DOS_PATH_MAX]; FCB_CHECK(!dos_canonical("C:",cwd));
    DosRegs saved={.ax=0x2f00}; FCB_CHECK(!FCB_CALL(&saved));
    FCB_CHECK(!dos_mkdir("C:\\FCBWORK") && !dos_chdir("C:\\FCBWORK"));
    u8 area[1026]; memset(area,0xa5,sizeof(area)); u8 *data=area+1;
    FCB_CHECK(!fcb_test_dta(data,1024));
    DosFcb f,copy; u8 *b=f.bytes; u32 records,n,pos; unsigned h,other;
    FCB_CHECK(!fcb_test_name(&f,"c:data.bin") && b[0]==3 && !memcmp(b+1,"DATA    BIN",11));
    memset(b+16,0x6b,21); const char *text=" ;  c:longfilename.*;tail";
    DosRegs r={.ax=0x2901,.si=(uintptr_t)text,.di=(uintptr_t)b};
    FCB_CHECK(!FCB_CALL(&r) && r.ax==1 && !r.bx && !strcmp((const char *)(uintptr_t)r.si,";tail"));
    FCB_CHECK(!memcmp(b+1,"LONGFILE???",11) && b[16]==0x6b && b[36]==0x6b);
    text=".new"; r=(DosRegs){.ax=0x290e,.si=(uintptr_t)text,.di=(uintptr_t)b};
    FCB_CHECK(!FCB_CALL(&r) && !r.ax && !memcmp(b+1,"LONGFILENEW",11) && b[0]==3);
    text="z:no.dat"; r=(DosRegs){.ax=0x2900,.si=(uintptr_t)text,.di=(uintptr_t)b};
    FCB_CHECK(!FCB_CALL(&r) && r.ax==255 && r.bx==DE_DRIVE);
    FCB_CHECK(!fcb_test_name(&f,"c:data.bin")); b[32]=5; wr32(b+33,0x12345678);
    FCB_CHECK(!fcb_test_call(0x16,&f,NULL,0) && rd16(b+14)==128 && b[32]==5 && rd32(b+33)==0x12345678);
    b[32]=0; wr16(b+14,16);
    for(unsigned i=0;i<32;i++) data[i]=(u8)i;
    FCB_CHECK(!fcb_test_call(0x15,&f,NULL,0) && b[32]==1 && rd32(b+16)==16);
    memcpy(data,data+16,16);
    FCB_CHECK(!fcb_test_call(0x15,&f,NULL,0) && b[32]==2 && rd32(b+16)==32);
    copy=f; copy.bytes[32]=0; memset(data,0xcc,32);
    FCB_CHECK(!fcb_test_call(0x14,&copy,NULL,0) && copy.bytes[32]==1 && b[32]==2);
    for(unsigned i=0;i<16;i++) FCB_CHECK(data[i]==i);
    wr32(b+33,1); wr16(b+12,7); b[32]=9;
    FCB_CHECK(!fcb_test_call(0x21,&f,NULL,0) && !rd16(b+12) && b[32]==1 && rd32(b+33)==1);
    for(unsigned i=0;i<16;i++) FCB_CHECK(data[i]==i+16);
    wr16(b+14,10); wr32(b+33,0); records=4; memset(data,0xcc,50);
    FCB_CHECK(!fcb_test_call(0x27,&f,&records,3) && records==4 && rd32(b+33)==4 && b[32]==4);
    for(unsigned i=0;i<40;i++) FCB_CHECK(data[i]==(i<32?i:0));
    FCB_CHECK(data[40]==0xcc);
    records=1; FCB_CHECK(!fcb_test_call(0x27,&f,&records,1) && !records && rd32(b+33)==4);
    FCB_CHECK(!fcb_test_dta(data,15)); wr32(b+33,0); records=3;
    FCB_CHECK(!fcb_test_call(0x28,&f,&records,2) && records==1 && rd32(b+33)==1);
    FCB_CHECK(!fcb_test_dta(data,9)); unsigned previous=b[32];
    FCB_CHECK(!fcb_test_call(0x14,&f,NULL,2) && b[32]==previous);
    FCB_CHECK(!fcb_test_dta(NULL,0)); records=0;
    FCB_CHECK(!fcb_test_call(0x27,&f,&records,0) && !records);
    wr16(b+14,1); wr32(b+33,20); records=0;
    FCB_CHECK(!fcb_test_call(0x28,&f,&records,0) && rd32(b+16)==20);
    FCB_CHECK(!fcb_test_dta(data,1024)); wr32(b+33,30); records=2; memcpy(data,"XY",2);
    FCB_CHECK(!fcb_test_call(0x28,&f,&records,0) && records==2 && rd32(b+16)==32);
    wr32(b+33,20); records=12; memset(data,0xcc,16);
    FCB_CHECK(!fcb_test_call(0x27,&f,&records,0) && records==12);
    for(unsigned i=0;i<10;i++) FCB_CHECK(!data[i]);
    FCB_CHECK(data[10]=='X' && data[11]=='Y' && data[12]==0xcc);
    wr16(b+14,128); wr16(b+12,1); b[32]=133; b[36]=0x5a;
    FCB_CHECK(!fcb_test_call(0x24,&f,NULL,0) && rd32(b+33)==0x5a000085);
    wr16(b+14,1); FCB_CHECK(!fcb_test_call(0x24,&f,NULL,0) && rd32(b+33)==133);
    wr16(b+14,0); b[36]=0x5a;
    FCB_CHECK(!fcb_test_call(0x24,&f,NULL,0) && rd32(b+33)==133 && !rd16(b+14));
    wr32(b+16,7); wr16(b+20,0x285d); wr16(b+22,0x645c); copy=f;
    FCB_CHECK(!fcb_test_call(0x10,&f,NULL,0));
    FCB_CHECK(!fcb_test_call(0x10,&copy,NULL,0));
    FCB_CHECK(fcb_test_call(0x14,&copy,NULL,1)==DE_HANDLE);
    FCB_CHECK(!dos_open("C:DATA.BIN",DOS_OPEN_RDWR,0,&h));
    u16 date=0,time=0; FCB_CHECK(!dos_seek(h,0,2,&pos) && pos==7);
    FCB_CHECK(!dos_file_time(h,0,&date,&time) && date==0x285d && time==0x645c);
    FCB_CHECK(!fcb_test_call(0x0f,&f,NULL,0)); wr16(b+14,1); b[32]=0;
    FCB_CHECK(!dos_lock(h,0,0,1));
    FCB_CHECK(fcb_test_call(0x14,&f,NULL,1)==DE_LOCK);
    wr32(b+16,0); FCB_CHECK(fcb_test_call(0x10,&f,NULL,255)==DE_LOCK);
    FCB_CHECK(!dos_lock(h,1,0,1));
    FCB_CHECK(!dos_seek(h,0,2,&pos) && pos==7);
    FCB_CHECK(!fcb_test_call(0x0f,&f,NULL,0));
    FCB_CHECK(!dos_write(h,"more",4,&n) && n==4); date=0x285e; time=0x1234;
    FCB_CHECK(!dos_file_time(h,1,&date,&time));
    FCB_CHECK(!fcb_test_call(0x10,&f,NULL,0));
    FCB_CHECK(!dos_seek(h,0,2,&pos) && pos==11);
    FCB_CHECK(!dos_file_time(h,0,&date,&time) && date==0x285e && time==0x1234);
    FCB_CHECK(!dos_close(h));
    FCB_CHECK(!dos_open("C:DATA.BIN",DOS_SHARE_DENY_WRITE,0,&h));
    FCB_CHECK(fcb_test_call(0x0f,&f,NULL,255)==DE_SHARE); FCB_CHECK(!dos_close(h));
    u8 attr=FA_RDONLY; FCB_CHECK(!dos_attribute("C:DATA.BIN",1,&attr));
    FCB_CHECK(!fcb_test_call(0x0f,&f,NULL,0)); wr16(b+14,1); b[32]=0;
    FCB_CHECK(!fcb_test_call(0x14,&f,NULL,0));
    FCB_CHECK(fcb_test_call(0x15,&f,NULL,1)==DE_ACCESS);
    FCB_CHECK(!fcb_test_call(0x10,&f,NULL,0)); attr=0;
    FCB_CHECK(!dos_attribute("C:DATA.BIN",1,&attr));
    FCB_CHECK(!fcb_test_name(&f,"c:data.bin")); wr16(b+14,4);
    FCB_CHECK(!fcb_test_call(0x23,&f,NULL,0) && rd32(b+33)==3);
    FCB_CHECK(!fcb_test_name(&f,"c:one.dat") && !fcb_test_call(0x16,&f,NULL,0) && !fcb_test_call(0x10,&f,NULL,0));
    FCB_CHECK(!fcb_test_name(&f,"c:two.dat") && !fcb_test_call(0x16,&f,NULL,0) && !fcb_test_call(0x10,&f,NULL,0));
    FCB_CHECK(!fcb_test_name(&f,"c:???.dat")); memcpy(b+17,"???     NEW",11);
    FCB_CHECK(!fcb_test_call(0x17,&f,NULL,0));
    FCB_CHECK(!fcb_test_name(&f,"c:*.new") && !fcb_test_dta(data,33));
    data[33]=0x5a; FCB_CHECK(!fcb_test_call(0x11,&f,NULL,0));
    FCB_CHECK(data[0]==3 && !memcmp(data+1,"ONE     NEW",11) && data[33]==0x5a);
    copy=f; FCB_CHECK(!fcb_test_call(0x0f,data,NULL,0) && !fcb_test_call(0x10,data,NULL,0));
    FCB_CHECK(!dos_chdir("C:\\"));
    FCB_CHECK(!fcb_test_call(0x12,&copy,NULL,0) && !memcmp(data+1,"TWO     NEW",11));
    FCB_CHECK(fcb_test_call(0x12,&copy,NULL,255)==DE_NOMORE);
    FCB_CHECK(!dos_chdir("C:\\FCBWORK"));
    r=(DosRegs){.ax=0x4e00,.dx=(uintptr_t)"C:*.*"}; FCB_CHECK(FCB_CALL(&r)==DE_NOMEM);
    FCB_CHECK(!fcb_test_dta(data,sizeof(DosFind))); data[sizeof(DosFind)]=0x5a;
    r=(DosRegs){.ax=0x4e00,.dx=(uintptr_t)"C:DATA.BIN"}; FCB_CHECK(!FCB_CALL(&r));
    DosFind ordinary; memcpy(&ordinary,data,sizeof(ordinary));
    FCB_CHECK(!strcmp(ordinary.name,"DATA.BIN") && ordinary.size==11 && data[sizeof(DosFind)]==0x5a);
    FCB_CHECK(!fcb_test_call(0x13,&f,NULL,0));
    FCB_CHECK(fcb_test_call(0x13,&f,NULL,255)==DE_NOMORE);
    DosExtendedFcb ext={.marker=255,.attr=FA_HIDDEN};
    FCB_CHECK(!fcb_test_name(&ext.fcb,"c:hidden.dat"));
    FCB_CHECK(!fcb_test_call(0x16,&ext,NULL,0) && !fcb_test_call(0x10,&ext,NULL,0));
    f=ext.fcb; FCB_CHECK(fcb_test_call(0x0f,&f,NULL,255)==DE_NOFILE);
    FCB_CHECK(!fcb_test_call(0x0f,&ext,NULL,0) && !fcb_test_call(0x10,&ext,NULL,0));
    FCB_CHECK(!fcb_test_dta(data,39)); FCB_CHECK(fcb_test_call(0x11,&ext,NULL,255)==DE_NOMEM);
    FCB_CHECK(!fcb_test_dta(data,40)); data[40]=0x5a;
    FCB_CHECK(!fcb_test_call(0x11,&ext,NULL,0));
    FCB_CHECK(data[0]==255 && !data[1] && data[6]==FA_HIDDEN && data[7]==3 && !memcmp(data+8,"HIDDEN  DAT",11) && data[40]==0x5a);
    FCB_CHECK(!fcb_test_call(0x13,&ext,NULL,0));
    ext=(DosExtendedFcb){.marker=255,.attr=FA_VOLUME}; ext.fcb.bytes[0]=3;
    memset(ext.fcb.bytes+1,'?',11); FCB_CHECK(!fcb_test_call(0x11,&ext,NULL,0));
    u8 original_label[11]; memcpy(original_label,data+8,11);
    FCB_CHECK(!fcb_test_call(0x13,&ext,NULL,0));
    memcpy(ext.fcb.bytes+1,"FCB VOLUME ",11);
    FCB_CHECK(!fcb_test_call(0x16,&ext,NULL,0) && !fcb_test_call(0x10,&ext,NULL,0));
    FCB_CHECK(fcb_test_call(0x16,&ext,NULL,255)==DE_ACCESS);
    FCB_CHECK(fcb_test_call(0x0f,&ext,NULL,255)==DE_ACCESS);
    FCB_CHECK(!fcb_test_call(0x11,&ext,NULL,0) && !memcmp(data+8,"FCB VOLUME ",11));
    memcpy(ext.fcb.bytes+17,"FCB RENAMED",11);
    FCB_CHECK(!fcb_test_call(0x17,&ext,NULL,0));
    memcpy(ext.fcb.bytes+1,"FCB RENAMED",11); ext.attr=FA_VOLUME|FA_ARCHIVE;
    FCB_CHECK(!fcb_test_call(0x11,&ext,NULL,0) && data[6]==(FA_VOLUME|FA_ARCHIVE) && !memcmp(data+8,"FCB RENAMED",11));
    FCB_CHECK(!fcb_test_call(0x13,&ext,NULL,0));
    memcpy(ext.fcb.bytes+1,original_label,11); ext.attr=FA_VOLUME;
    FCB_CHECK(!fcb_test_call(0x16,&ext,NULL,0) && !fcb_test_call(0x10,&ext,NULL,0));
    FCB_CHECK(!fcb_test_name(&f,"c:data.bin"));
    for(unsigned i=0;i<70;i++) FCB_CHECK(!fcb_test_call(0x0f,&f,NULL,0));
    FCB_CHECK(!fcb_test_call(0x10,&f,NULL,0));
    unsigned handles[15];
    for(unsigned i=0;i<15;i++) FCB_CHECK(!dos_open("NUL",2,0,&handles[i]));
    FCB_CHECK(!fcb_test_call(0x0f,&f,NULL,0));
    FCB_CHECK(dos_open("NUL",2,0,&other)==DE_HANDLES);
    FCB_CHECK(dos_open("NUL",3,0,&other)==DE_MODE);
    FCB_CHECK(dos_open_ex("NUL",2,0,0,&other,&n)==DE_FUNCTION);
    FCB_CHECK(!fcb_test_call(0x10,&f,NULL,0));
    for(unsigned i=0;i<15;i++) FCB_CHECK(!dos_close(handles[i]));
    FCB_CHECK(!fcb_test_name(&f,"nul") && !fcb_test_call(0x0f,&f,NULL,0));
    FCB_CHECK(!fcb_test_dta(data,1024));
    wr16(b+14,0);
    FCB_CHECK(!fcb_test_call(0x14,&f,NULL,1) && !fcb_test_call(0x15,&f,NULL,0));
    FCB_CHECK(rd16(b+14)==128);
    wr16(b+14,65535); wr32(b+33,0xffffff); records=1;
    FCB_CHECK(fcb_test_call(0x27,&f,&records,1)==DE_SEEK && !records);
    r=(DosRegs){.ax=0x2800,.dx=(uintptr_t)&f,.cx=1ULL<<32};
    FCB_CHECK(!FCB_CALL(&r) && r.ax==1 && r.bx==DE_FUNCTION && !r.cx);
    FCB_CHECK(!fcb_test_call(0x10,&f,NULL,0));
    r=(DosRegs){.ax=0x1a01,.dx=UINTPTR_MAX-3,.cx=8}; FCB_CHECK(FCB_CALL(&r)==DE_FUNCTION);
    r=(DosRegs){.ax=0x2f00}; FCB_CHECK(!FCB_CALL(&r) && r.bx==(uintptr_t)data && r.cx==1024);
    FCB_CHECK(area[0]==0xa5 && area[1025]==0xa5);
    FCB_CHECK(!dos_remove("C:DATA.BIN",0));
    FCB_CHECK(!dos_chdir(cwd) && !dos_remove("C:\\FCBWORK",1));
    FCB_CHECK(!dos_open("C:\\FCBKEEP.DAT",2,1,&h) && !dos_write(h,"fcb!!",5,&n) && n==5);
    date=0x285d; time=0x645c; FCB_CHECK(!dos_file_time(h,1,&date,&time) && !dos_close(h));
    r=(DosRegs){.ax=0x1a01,.dx=saved.bx,.cx=saved.cx}; FCB_CHECK(!FCB_CALL(&r));
    return 0;
}
