#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Build console code-page translation tables from Python's standard codecs.

The output is a native table file for CON code-page preparation, not an IBM
FONT CPI file: the EFI console renders Unicode, so only byte <-> UTF-16 maps
are needed. A page is emitted only when its Python codec verifiably matches
the DOS 4 page structure, including the DBCS lead ranges in COUNTRY.SYS.
"""
from pathlib import Path
import codecs
import struct
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
from mkcountry import SOURCE, DataAssembler, country_records  # noqa: E402

MAGIC = b'\xffUNICODE'
VERSION = 1
SBCS, DBCS = 1, 2
# DOS page -> Python codec. 934 (IBM Korean PC, leads 81-BF), 936 (IBM
# S-Chinese PC, leads 81-FC) and 938 (IBM T-Chinese PC, leads 81-FC) have no
# matching standard-library codec: cp949/euc_kr/johab, GBK and Big5 use other
# lead ranges or byte assignments, so they are deliberately not generated.
CODECS = {437: 'cp437', 850: 'cp850', 860: 'cp860', 862: 'cp862', 863: 'cp863',
          864: 'cp864', 865: 'cp865', 932: 'cp932'}


def private(text):
    return any(0xe000 <= ord(c) <= 0xf8ff or 0xdc80 <= ord(c) <= 0xdcff for c in text)


def unit(raw, codec):
    """Map one byte sequence to one BMP code unit; 0 means unmapped."""
    try:
        text = raw.decode(codec)
    except UnicodeDecodeError:
        return 0
    if len(text) != 1 or private(text) or ord(text) > 0xffff:
        return 0
    if not ord(text) and raw != b'\0':
        return 0
    return ord(text)


def leads_from(table):
    leads = set()
    for i in range(0, len(table) - 2, 2):
        if table[i] or table[i + 1]:
            leads.update(range(table[i], table[i + 1] + 1))
    return leads


def page_table(page, codec, dbcs):
    leads = leads_from(dbcs)
    single = [0 if b in leads else unit(bytes([b]), codec) for b in range(256)]
    if not leads:
        if any(single[b] != b for b in range(32)):
            raise ValueError(f'{page}: control bytes are not identity mapped')
        return SBCS, struct.pack('<256H', *single), single
    # Verify the codec's own DBCS structure against the DOS lead table: a DOS
    # lead byte must be incomplete alone (some rows are legitimately empty);
    # any other byte must never combine with a following byte.
    for b in range(256):
        try:
            bytes([b]).decode(codec)
            alone = True
        except UnicodeDecodeError:
            alone = False
        if b in leads:
            if alone:
                raise ValueError(f'{page}: DOS lead byte {b:02X} decodes alone')
        else:
            for t in range(0x40, 0x100):
                try:
                    if len(bytes([b, t]).decode(codec)) == 1:
                        raise ValueError(f'{page}: byte {b:02X} combines but is not a DOS lead')
                except UnicodeDecodeError:
                    pass
    mapped = sum(1 for lead in leads for t in range(0x40, 0x100) if unit(bytes([lead, t]), codec))
    if mapped < 1000:
        raise ValueError(f'{page}: only {mapped} double-byte characters')
    ranges = bytes(dbcs[:len(dbcs) - 2]) + b'\0\0'
    if len(ranges) > 16:
        raise ValueError(f'{page}: too many lead ranges')
    body = bytearray(ranges.ljust(16, b'\0'))
    body += struct.pack('<256H', *single)
    for lead in sorted(leads):
        body += struct.pack('<256H', *[unit(bytes([lead, t]), codec) if t >= 0x40 else 0 for t in range(256)])
    return DBCS, bytes(body), single


def build(output, header):
    records = country_records(DataAssembler().assemble(SOURCE))
    dbcs = {}
    for _, page, tables in records:
        if dbcs.setdefault(page, tables[7]) != tables[7]:
            raise ValueError(f'{page}: inconsistent DBCS tables')
    missing = sorted(set(dbcs) - set(CODECS))
    pages = []
    for page in sorted(CODECS):
        if page not in dbcs:
            raise ValueError(f'{page}: not a DOS 4 COUNTRY.SYS code page')
        codecs.lookup(CODECS[page])
        kind, body, single = page_table(page, CODECS[page], dbcs[page])
        pages.append((page, kind, body))
        if page == 437:
            builtin = single
    data = bytearray(MAGIC + struct.pack('<HH', VERSION, len(pages)))
    offset = len(data) + 12 * len(pages)
    for page, kind, body in pages:
        data += struct.pack('<HBBII', page, kind, 0, offset, len(body))
        offset += len(body)
    for _, _, body in pages:
        data += body
    Path(output).write_bytes(data)
    lines = ['/* Generated by tools/mkcodepage.py from Python codec cp437. */',
             'static const u16 builtin_cp437[256] = {']
    lines += ['    ' + ','.join(f'0x{v:04x}' for v in builtin[i:i + 12]) + ','
              for i in range(0, 256, 12)]
    Path(header).write_text('\n'.join(lines + ['};', '']), encoding='ascii')
    print(f'{output}: {len(data)} bytes, code pages {",".join(str(p) for p, _, _ in pages)}'
          f'; unsupported {",".join(str(p) for p in missing)}')


if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SystemExit('usage: mkcodepage.py EFI.CPI codepage_data.h')
    build(sys.argv[1], sys.argv[2])
