#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate CP437 VGA fonts (8 pixels wide, 8/14/16 rows) and Unicode maps.
Rows are bytes, MSB leftmost. The large Unicode BDF supplies 16-row glyphs;
keep 8 columns because VGA repeats column 8 for C0h-DFh in 9-dot mode.
Align short glyphs to baseline 12 and stretch box/block glyphs to join cells.
The 14-row font uses rows 1-14, resampling box/block glyphs. The small BDF
supplies 8-row glyphs from rows 1-8, shifted one column; resample boxes and
blocks, and synthesize shades. Codes 01h-1Fh/7Fh use IBM PC symbols.

Usage: mkvgafont.py output.h large.bdf small.bdf height... [graftabl]
'graftabl' adds 850/860/863/865 characters 80h-FFh for INT 1Fh."""
import sys
from mkfont import parse

SYMBOLS = [0x0000, 0x263a, 0x263b, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022, 0x25d8, 0x25cb, 0x25d9, 0x2642,
           0x2640, 0x266a, 0x266b, 0x263c, 0x25ba, 0x25c4, 0x2195, 0x203c, 0x00b6, 0x00a7, 0x25ac, 0x21a8,
           0x2191, 0x2193, 0x2192, 0x2190, 0x221f, 0x2194, 0x25b2, 0x25bc]
SHADES = {0x2591: (0x22, 0x88), 0x2592: (0x55, 0xaa), 0x2593: (0xdd, 0x77)}

GRAFTABL_PAGES = (850, 860, 863, 865)
def point(code, page=437):
    if code < 0x20:
        return SYMBOLS[code]
    if code == 0x7f:
        return 0x2302
    return ord(bytes([code]).decode('cp%d' % page))

def boxy(p):
    return 0x2500 <= p <= 0x259f

def raster(font, code, height, page=437):
    """The glyph in a cell of the font's own height, left-aligned."""
    props, glyphs = font
    ascent = props['FONT_ASCENT']
    rows = [0] * height
    glyph = glyphs.get(point(code, page)) or (glyphs.get(ord('?')) if code else None)
    if glyph and code:
        w, h, x, y = glyph['bbx']
        row_bytes = (w + 7) // 8
        for i, bits in enumerate(glyph['rows']):
            r = ascent - (y + h) + i
            value = (bits << (16 - 8 * row_bytes)) & 0xffff  # left-aligned in 16 bits
            if 0 <= r < height:
                rows[r] = ((value >> x if x >= 0 else value << -x) >> 8) & 0xff
    return rows

def large(font, code):
    props = font[0]
    width, height = props['FONTBOUNDINGBOX'][:2]
    assert width in (8, 9) and height <= 16, (width, height)
    rows = raster(font, code, height)
    if boxy(point(code)):
        return [rows[r * height // 16] for r in range(16)]
    top = 12 - props['FONT_ASCENT']
    cell = [0] * 16
    for r, v in enumerate(rows):
        if 0 <= top + r < 16:
            cell[top + r] = v
    return cell

def small(font, code, page=437):
    props = font[0]
    width, height = props['FONTBOUNDINGBOX'][:2]
    assert width <= 7 and height == 10, (width, height)
    p = point(code, page)
    if p in SHADES:
        return [SHADES[p][r & 1] for r in range(8)]
    rows = raster(font, code, height, page)
    if boxy(p):
        bit = lambda v, c: v >> (7 - c) & 1
        return [sum(bit(rows[r * height // 8], c * width // 8) << (7 - c) for c in range(8)) for r in range(8)]
    return [v >> 1 for v in rows[1:9]]

def main(output, large_source, small_source, *heights):
    big, little = parse(large_source), parse(small_source)
    fonts = {}
    graftabl = 'graftabl' in heights
    heights = [h for h in heights if h != 'graftabl']
    for height in map(int, heights):
        if height == 16:
            fonts[16] = [large(big, c) for c in range(256)]
        elif height == 14:
            fonts[14] = [[cell[r * 16 // 14] for r in range(14)] if boxy(point(c)) else cell[1:15]
                         for c, cell in enumerate(large(big, c) for c in range(256))]
        elif height == 8:
            fonts[8] = [small(little, c) for c in range(256)]
        else:
            raise SystemExit('height %d' % height)
    with open(output, 'w', encoding='ascii') as out:
        out.write('/* Generated by tools/mkvgafont.py from %s and %s; public domain glyphs. */\n'
                  % (large_source.split('/')[-1], small_source.split('/')[-1]))
        for height, cells in sorted(fonts.items()):
            out.write('static const unsigned char vga_font%d[256][%d]={\n' % (height, height))
            for code, cell in enumerate(cells):
                out.write('    {%s}, /* %02x */\n' % (','.join('0x%02x' % v for v in cell), code))
            out.write('};\n')
        if graftabl:
            out.write('static const unsigned short vga_graftabl_pages[%d]={%s};\n'
                      % (len(GRAFTABL_PAGES), ','.join(str(p) for p in GRAFTABL_PAGES)))
            out.write('static const unsigned char vga_graftabl[%d][128][8]={\n' % len(GRAFTABL_PAGES))
            for page in GRAFTABL_PAGES:
                out.write('  { /* %d */\n' % page)
                for code in range(128, 256):
                    out.write('    {%s},\n' % ','.join('0x%02x' % v for v in small(little, code, page)))
                out.write('  },\n')
            out.write('};\n')
        out.write('static const unsigned short vga_unicode[256]={\n')
        for base in range(0, 256, 16):
            out.write('    %s,\n' % ','.join('0x%04x' % point(c) for c in range(base, base + 16)))
        out.write('};\n')

if __name__ == '__main__':
    main(*sys.argv[1:])
