#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Copy windows.h's numeric constants into a header rc.exe can include
(rc.exe cannot read the C declarations)."""
import re, sys

def main(source, output):
    out = ['/* Generated by tools/mkwindefs.py from %s. */' % source.split('/')[-1]]
    names = set()
    for line in open(source, encoding='ascii'):
        m = re.match(r'#define (\w+) (.+?)\s*$', line)
        if not m:
            continue
        name, value = m.groups()
        # Numbers, and expressions of numbers and constants already taken.
        tokens = re.findall(r'[A-Za-z_]\w*', value)
        if not re.fullmatch(r'[\w\s()|+\-<>~*]+', value) or any(t not in names and not re.fullmatch(r'0[xX][0-9a-fA-F]+[lLuU]*|\d+[lLuU]*', t) for t in tokens):
            if not re.fullmatch(r'\(?-?(0[xX][0-9a-fA-F]+|\d+)[lLuU]*\)?', value):
                continue
        names.add(name)
        out.append('#define %s %s' % (name, value))
    open(output, 'w', encoding='ascii').write('\n'.join(out) + '\n')

if __name__ == '__main__':
    main(*sys.argv[1:])
